# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ISTAT": "00_base.ipynb",
         "parse_dataflows": "01_discovery.ipynb",
         "all_available": "01_discovery.ipynb",
         "search_dataset": "01_discovery.ipynb",
         "DataSet": "01_discovery.ipynb",
         "make_tree": "02_utils.ipynb",
         "strip_ns": "02_utils.ipynb",
         "get_data": "03_retrieval.ipynb",
         "set_filters": "03_retrieval.ipynb",
         "make_url_key": "03_retrieval.ipynb",
         "RESOURCE": "03_retrieval.ipynb"}

modules = ["base.py",
           "discovery.py",
           "utils.py",
           "retrieval.py"]

doc_url = "https://Attol8.github.io/istatapi/"

git_url = "https://github.com/Attol8/istatapi/tree/master/"

def custom_doc_links(name):
    return None
