# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ISTAT": "00_base.ipynb",
         "DataFlows": "01_discovery.ipynb",
         "DataStructure": "01_discovery.ipynb",
         "make_tree": "02_utils.ipynb",
         "strip_ns": "02_utils.ipynb"}

modules = ["base.py",
           "utils.py"]

doc_url = "https://Attol8.github.io/istatapi/"

git_url = "https://github.com/Attol8/istatapi/tree/master/"

def custom_doc_links(name): return None
