# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_utils.ipynb.
# Patched: replaced ET.iterparse with ET.parse to fix tree.root access after strip_ns.

# %% auto 0
__all__ = ['make_tree', 'strip_ns']

# %% ../nbs/02_utils.ipynb 1
import xml.etree.ElementTree as ET
from io import StringIO


# %% ../nbs/02_utils.ipynb 4
def make_tree(response):
    """Make an `ElementTree` from the text of an XML `response`"""
    # FIX: use ET.parse instead of ET.iterparse.
    # ET.iterparse returns a lazy iterator; calling strip_ns exhausts it,
    # making tree.root inaccessible afterwards. ET.parse returns a proper
    # ElementTree object with a persistent .getroot() / .root attribute.
    tree = ET.parse(StringIO(response.text))
    return tree


def strip_ns(tree):
    """Strip all namespaces from element tags in `tree` (modifies in place)"""
    # FIX: ET.parse returns an ElementTree, so we iterate via tree.iter()
    for el in tree.iter():
        _, _, el.tag = el.tag.rpartition('}')  # strip ns
    return tree
